### ISSUE TITLE
[enhancement] Support for DuckDB

### ISSUE THREAD

**Issue by felipevalerio** [nomadiz/edma#7]
**Is your feature request related to a problem? Please describe.**
DuckDB is an embeddable analytical database, think SQLite but OLAP.
It would be great to have a support for this tool

**Additional context**
Their github: https://github.com/duckdb/duckdb

**Comment by chungquantin** [comment]
For now, EDMA is compatible with embedded storages only. I'm afraid that DucksDB can't be integrated into EDMA as it is a relational database. I think Gobang is a more preferable option for your use case: https://github.com/TaKO8Ki/gobang
